CREATE TABLE IF NOT EXISTS member (
  MemberId INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL DEFAULT '',
  Email VARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(30) DEFAULT NULL,
  Password VARCHAR(500) CHARACTER NOT NULL,
  CreatedDate TIMESTAMP NULL ,
  MemberStory VARCHAR(500) CHARACTER  DEFAULT NULL,
  PRIMARY KEY (MemberId)
);

CREATE TABLE IF NOT EXISTS topic (
  TopicId INT(11) NOT NULL AUTO_INCREMENT,
  TopicDescription VARCHAR(255) DEFAULT NULL,
  TopicName VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (topicId)
);

CREATE TABLE IF NOT EXISTS memberblogpost (
  blogPostId INT(11) NOT NULL AUTO_INCREMENT,
  BlogPostBody VARCHAR(255) DEFAULT NULL,
  BlogPostTitle VARCHAR(255) DEFAULT NULL,
  DatePosted DATETIME DEFAULT NULL,
  MemberAuthorId BIGINT(20) NOT NULL,
  TopicId INT(11) NOT NULL,
  PRIMARY KEY (blogPostId),
  CONSTRAINT FK_Topic_MEMBERBLOGPOST FOREIGN KEY (TopicId)
    REFERENCES topic(topicId) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_MEMBER_MEMBERBLOGPOST FOREIGN KEY (MemberAuthorId)
    REFERENCES MEMBER(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

