CREATE TABLE IF NOT EXISTS member (
  MemberId INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL DEFAULT '',
  Email VARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(30) DEFAULT NULL,
  Password VARCHAR(500) CHARACTER NOT NULL,
  CreatedDate TIMESTAMP NULL ,
  MemberStory VARCHAR(500) CHARACTER  DEFAULT NULL,
  PRIMARY KEY (MemberId)
);